### ISSUE TITLE
Player can still navigate with the back button when out of fuel. Also, the label and button do not get displayed properly when traveling up the tree

### ISSUE THREAD

**Issue by jonathanmcdaniel** [RyanYoung25/UndiscoveredWorlds#15]

**Comment by RyanYoung25** [comment]
If no one is currently editing it I will take over the fuel responsibilities. The only thing I need is an end of game screen.

**Comment by jonathanmcdaniel** [comment]
Im done coding for the day. I have an exam to study for. Its yours if you want it.

**Comment by jonathanmcdaniel** [comment]
If you want just create a method that returns a jframe or joption pane or something and I will add the gui into that
