### ISSUE TITLE
Problem with fuel level

### ISSUE THREAD

**Issue by RyanYoung25** [RyanYoung25/UndiscoveredWorlds#16]
Hey there is a kind of big problem with the fuel level. When you use the fuel in the inventory screen you actually lose fuel. I like the fuel display on the main gui but I don't think that we should count the fuel in the inventory as fuel. The reason I say this is because fuel is a commodity too and it would be more logical to implement it as a use then get more fuel. I don't know right now who is doing what so I don't know if I can fix this or if someone is already on it.

**Comment by pixelhater** [comment]
The way the method works it doesn't actually put the fuel in the tank. When get fuel is called it gets the current fuel plus any fuel items. The fuel items are only actually used in two cases: when used in inventory and when current fuel level is zero. For example: if fuel level is 30, that means the current tank is 5 and the player has a hydrogen fuel item. When a move is made, the hydrogen fuel item is automatically expended, which leaves the fuel level at 25. If there actually is a bug and fuel is used when it shouldn't be, let me know the exact conditions required to recreate the bug. I can't seem to create a situation where this happens.

**Comment by RyanYoung25** [comment]
I read the code and know how it works. Should we let the fuel level be above the max fuel level and if so why have a max fuel level and the bug is really easy to recreate. Just buy fuel and count the number of moves. Then when you actually use the fuel you get less number of moves. Or look at the number. 

The easiest fix I have in mind for this is just show them the fuel level excluding the fuel in the inventory. The automatic fuel consumption is nice though.

**Comment by pixelhater** [comment]
Switched it back to previous implementation for simplicity's sake. Too late in the game to be playing around with something that might confuse the player.
