### ISSUE TITLE
FileOps Error

### ISSUE THREAD

**Issue by jonathanmcdaniel** [RyanYoung25/UndiscoveredWorlds#2]
The file cannot locate the text files. Im not sure how to fix it with the way Bryant has it set up. Ill keep looking at it but it may be a faster fix if he does it. The text files are located in the bin folder not src and the file path is relative to the bin directory not the project folder.

**Comment by pixelhater** [comment]
I just pushed an update that fixes the issue from the command line. To get this to run in Eclipse, I had to change the run configuration for the GalaxyTest. In the 'Arguments' tab select 'Other' for working directory and either search for the 'bin' directory or input the following: ${workspace_loc:UndiscoveredWorlds/bin}

If there are still issues, let me know and I'll continue working the issue.

**Comment by jonathanmcdaniel** [comment]
That works for me.
