### ISSUE TITLE
Finishing the Game

### ISSUE THREAD

**Issue by RyanYoung25** [RyanYoung25/UndiscoveredWorlds#20]
Jon, can you make the panel or frame or what ever you want happen when the game ends. There is an if statement in SpacePanel where the winning will go and just put it there.

**Comment by jonathanmcdaniel** [comment]
Will do. One the pane should there should be a button to quit back to the main menu right? Anything else you want?

**Comment by RyanYoung25** [comment]
Just a happy ending

----- Reply message -----

**Comment by jonathanmcdaniel** [comment]
Added a Joptionpane that moves the player to the main menu. Also gives the option to keep playing since it looks like that method gets called whenever the player hits the back button.
