### ISSUE TITLE
Bug Fixing/ Enhancement

### ISSUE THREAD

**Issue by RyanYoung25** [RyanYoung25/UndiscoveredWorlds#21]
Hey Tanya,

Here are a couple of bugs to fix. I sent you an email with them too. : 

-Disable back button at zero fuel. Re enable when player has fuel.
-Double clicking in the trade menu

When you get it done you can ask me or Bryant for more.

**Comment by jonathanmcdaniel** [comment]
We were having some issues with the "-Disable back button at zero fuel. Re enable when player has fuel." issue. We decided to make the player lose when they run out of fuel so we just removed all of the GUI except for the button to quit the game.

**Comment by murzila** [comment]
Ok. #2 is done.

**Comment by jonathanmcdaniel** [comment]
Make sure you push it

**Comment by jonathanmcdaniel** [comment]
Nevermind. Didn't see it
