### ISSUE TITLE
Music

### ISSUE THREAD

**Issue by RyanYoung25** [RyanYoung25/UndiscoveredWorlds#22]
Hey this is an easy one. I have a class that can play music so do we want to add some music to the game?

**Comment by jonathanmcdaniel** [comment]
Go for it if you want. Just make sure all coding is finished before class tomorrow.

**Comment by murzila** [comment]
I do not mind if the music is appropriate for the game.

**Comment by RyanYoung25** [comment]
Ok you find the music I will make it work. Just get me the file

**Comment by pixelhater** [comment]
I think it might be a good idea to not add something new this late in the game. Unintended side effects could cause unforeseen problems. Also, this may impact requirements in ways we can evaluate easily.

**Comment by jonathanmcdaniel** [comment]
That's actually true. We already have most, if not all of the bugs fixed. I think we should more or less stick with what we have. You can add it to the game after its graded if you want to though just for the game's sake.
