### ISSUE TITLE
GUI Suggestion

### ISSUE THREAD

**Issue by pixelhater** [RyanYoung25/UndiscoveredWorlds#3]
When displaying a location, it might be a good idea to render it first and then place markers on all of the locations that the player can visit. You could also vary the marker to denote the presence of a TradePort. This should get around having to reference locations using the coordinates of the mouse cursor.

**Comment by RyanYoung25** [comment]
Bryant was telling me about this and I think it is a really good idea. If you need any help with it Jon or Tanya just push the code you have and I think I have an idea of doing it. That or we can meet and talk it out.

**Comment by jonathanmcdaniel** [comment]
Yeah I actually need to meet with you guys about the GUI. Preferably Monday or Tuesday. We have to do a little bit of rewriting to make the merchant generate with the ports and have all of the classes talk to each other. I also need you guys to label or tell me which classes of yours are meant to be the main (displayed) class so that I can implement them.

**Comment by RyanYoung25** [comment]
I can help you with that Jon, Can you meet after 3:30 on monday?

**Comment by jonathanmcdaniel** [comment]
Yeah that's good for me

**Comment by pixelhater** [comment]
I'm good for anytime after 1230 on monday, and Tanya is good anytime after noon on Monday.

**Comment by jonathanmcdaniel** [comment]
I'm done at noon as well. Ill have to get lunch though

**Comment by murzila** [comment]
Jon and Bryant, can we meet at 1 pm on Monday? I work in the evening, so I will not be able to stay till 4. But then you can meet with Ryan after 3:30.

Jon, I think we can split work into two parts: navigation and graphical rendering. What part should I work on?

**Comment by jonathanmcdaniel** [comment]
That works perfectly for me. 

I would love it if you could figure out the rendering and representing the various clusters and planets in something tangible I am lost on this.

**Comment by murzila** [comment]
I'll try to figure it out. I'm sure Bryant or Ryan can help  if we have questions.

**Comment by pixelhater** [comment]
Let me know where we are meeting and what time and I'll show up.

**Comment by murzila** [comment]
1 pm on Monday in the basement of Creese Student Center (where we usually meet).
