### ISSUE TITLE
TradingMenu cost to wallet comparison

### ISSUE THREAD

**Issue by jonathanmcdaniel** [RyanYoung25/UndiscoveredWorlds#5]
I added a list listener to see when something is being selected in the list. The action then compares the selected item cost to the available funds in either the player or merchant wallet. This works perfectly fine on its own. However, when actually purchasing or selling items you begin to see some weird things happening to the list.

**Comment by RyanYoung25** [comment]
Hey Jon, if you leave that how it is I will fix/improve it tomorrow. Thanks for all the effort put into the trading but I want to play around with it and the item generation. If you could figure out the orbital clicking problem that would be very helpful.

Ryan

----- Reply message -----

**Comment by jonathanmcdaniel** [comment]
Let me know if this is least fixed. If not can you be a little more specific?
