### ISSUE TITLE
Can someone help me please... ?

### ISSUE THREAD

**Issue by murzila** [RyanYoung25/UndiscoveredWorlds#6]
I still can not run the code. I get an error when I try to run GalaxyTest or GUITest

Can't read input file!
Exception in thread "main" java.lang.NullPointerException
    at PictureAlbum.getClusterPic(PictureAlbum.java:76)
    at Cluster.<init>(Cluster.java:29)
    at Galaxy.<init>(Galaxy.java:22)
    at GalaxyTest.main(GalaxyTest.java:14)

**Comment by RyanYoung25** [comment]
Change where it's reading the file from in eclipse. It's under run configuration. 

Ryan

----- Reply message -----

**Comment by murzila** [comment]
Thank you, Ryan.
Finally, I figured out what was causing the problem. Eclipse (from both mac and windows side) can not navigate to the text files because of how the path is specified. If I put full paths, the program starts working, but I still get "Can not open the file!" error. After manually comparing images in the Art folder and what was loaded, I see that not all artwork got loaded for some reason.

Now the question is, when I work of the code, can I push? I had to specify full paths of text files to run the code.

**Comment by murzila** [comment]
These should work as universal paths:

For PictureAlbum: public static final String IMG_FOLDER = System.getProperty("user.dir") + File.separator + "bin" + File.separator + "Art" + File.separator; 

For FIleOps: public static final String NAMES_PATH = System.getProperty("user.dir") + File.separator + "src" + File.separator + "Names" + File.separator;

**Comment by jonathanmcdaniel** [comment]
We will have to look at this. I think it will cause issues when running from the command line. The code will automatically look for resources in the bin folder so the program will be unable to find the user directory there(its basically an invalid path). Eclipse however looks for resources beginning in the project folder. This is why some issues existed before we changed the run configuration.
