### ISSUE TITLE
Buttons are hard to see with backgrounds

### ISSUE THREAD

**Issue by jonathanmcdaniel** [RyanYoung25/UndiscoveredWorlds#7]
If you remove the box around the clickable items, it is nearly impossible to distinguish them from the background. Maybe lessen the details in the backgrounds? Or we could add some sort of ring around all of the buttons.

**Comment by pixelhater** [comment]
The intent is to render each entity and then use a navigational marker as the icon on the buttons. This is already implemented partially with rings.

**Comment by jonathanmcdaniel** [comment]
I think I kind of understand. Basically there will be some sort of pin or identifiable art on top of the current objects?

**Comment by jonathanmcdaniel** [comment]
Are your images semi transparent? I can see the background through a lot of the planets

**Comment by pixelhater** [comment]
Fixed the transparency issue. The scene was rendering backwards, so the starfield was overlaying everything else. Looks pretty good, but it could still do with a little tweaking.

**Comment by jonathanmcdaniel** [comment]
I think its coming along very nicely

**Comment by jonathanmcdaniel** [comment]
Is the top level scene rendering correctly? The buttons are hard to see (if at all) in the background. Is there an image on top of them?

**Comment by pixelhater** [comment]
Is everyone okay with the interface as it is now, or are modifications still required?
