### ISSUE TITLE
Trading GUI suggestion

### ISSUE THREAD

**Issue by pixelhater** [RyanYoung25/UndiscoveredWorlds#9]
Make the list automatically select another item in the inventory when something is bought/sold. This allows the player to click rapidly through inventory instead of having to click individual items.

**Comment by jonathanmcdaniel** [comment]
This is probably 1 to 3 lines of code somewhere within Ryan's code

**Comment by RyanYoung25** [comment]
Tanya actually was going to do this.

**Comment by murzila** [comment]
Yes, I will work on this today or tomorrow

**Comment by murzila** [comment]
Done!  It works fine on my computer. I just talked to Bryant, and for some reason the items do not get selected when he runs the code... So, we'll need to find out why this happens.

**Comment by jonathanmcdaniel** [comment]
It works for me!

**Comment by pixelhater** [comment]
Works me now too. I can't seem to recreate the bug, so I'm thinking it was just a fluke.

**Comment by RyanYoung25** [comment]
I'll check it out when I get home and have internet on my laptop. 

----- Reply message -----

**Comment by murzila** [comment]
Glad it works :)
